### ISSUE TITLE
Improvement: need to un-map the files in the generated CUDA code

### ISSUE THREAD

**Issue by JigaoLuo** [Henning1/dogqc#6]
There is no function call of `void unmap_memory_file ( void* ptr )` in the generated cuda code.
Thus, the memory-mapped files are not un-mapped in the end of the cuda program.

**Comment by Henning1** [comment]
This was done on purpose such that successive executions can access the in-memory data. Surely a non-prototype implementation would have to unmap the files. However, then, I think it is preferable not to use memory mapped files at all due to performance limitations.

**Comment by JigaoLuo** [comment]
I see. Thanks!
